        <div class="migrationAlert">

            <h2>SciServer Altair Update <i>f</i></h2>

            <p><strong>NEW:</strong> <a href="http://www.sciserver.org/support/updates/#overview1p9p1" target="_blank">SciServer 
                <em>Altair</em> Update <i>f</i>&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a>
              is now available! The update includes a new CrossMatch tool using  
              <a href="http://voservices.net/skyquery" target="_blank">SkyQuery&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a> services, 
              as well as links to the new <a href="http://dr13.sdss.org" target="_blank">SAW &nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a> web application, several bugfixes, 
              a new RStudio image in <a href="http://compute.sciserver.org" target="_blank">SciServer Compute&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a>
              and an improved SciServer <a href="http://portal.sciserver.org/login-portal/" target="_blank">Login-Portal&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png">
              </a>.</p>

        </div>
