        <div class="migrationAlert">

            <h2>SciServer Altair Update 4</h2>

            <p><strong>NEW:</strong> <a href="http://www.sciserver.org/support/updates/#overview1p8p2" target="_blank">SciServer 
                <em>Altair</em> Update 4&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a> 
                 is now available! The update includes several bugfixes to SkyServer, and a new Python image 
                with development tools in <a href="http://compute.sciserver.org" target="_blank">SciServer 
                 Compute&nbsp;<img alt=" (new window)" src="images/new_window_cyan.png"></a>.</p>

        </div>
