//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyServer.Tools.Search {
    
    
    public partial class IRQS {
        
        /// <summary>
        /// QS_Parameter1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Search.QS_Parameter QS_Parameter1;
        
        /// <summary>
        /// QS_Position1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Search.QS_Position QS_Position1;
        
        /// <summary>
        /// QS_IRSpec1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Search.QS_IRSpec QS_IRSpec1;
    }
}
