//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkyServer.Tools.Explore {
    
    
    public partial class Summary {
        
        /// <summary>
        /// loginParams control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.en.Loginfloat loginParams;
        
        /// <summary>
        /// MetadataParameters1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.MetaDataControl MetadataParameters1;
        
        /// <summary>
        /// ImagingParameters1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.ImagingControl ImagingParameters1;
        
        /// <summary>
        /// CrossId1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.CrossIdControls CrossId1;
        
        /// <summary>
        /// SpectralControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.SpectralControl SpectralControl1;
        
        /// <summary>
        /// ApogeeControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.ApogeeControl ApogeeControl1;
        
        /// <summary>
        /// MangaControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::SkyServer.Tools.Explore.MangaControl MangaControl1;
    }
}
